version: '3.6'
services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:latest
    environment:
      PRODUCTION: 'false'
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASE: bot
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "55432:5432"
    volumes:
      - $HOME/docker-db